fixed weather-switcher & timetable
NITKC-DEV/Kisarazu-Multi-Manager pull request #147
Opened 2023-06-29 04:17 UTC by starkoka

## バグ修正
 - #118 を修正
 - #129 を修正

## その他
 - #121 を適用

2023-06-29 04:17 UTC, starkoka commented
ちょい待ち

2023-06-29 04:22 UTC, starkoka commented
@NXVZBGBFBEN @Kou-Ro @naotiki 頼んだ！(ちなみに変更箇所半分ぐらいフッターなので、実質変更は20行程度)

2023-06-29 11:51 UTC, NXVZBGBFBEN requested changes
いっこだけ！

2023-06-29 11:51 UTC, NXVZBGBFBEN commented on commands/general.js
>  const {configPath} = require("../environmentConfig");
拡張子ほしい

2023-06-29 12:17 UTC, NXVZBGBFBEN submitted a review, later dismissed
```
   __   _____________  ___
  / /  / ___/_  __/  |/  /
 / /__/ (_ / / / / /|_/ / 
/____/\___/ /_/ /_/  /_/  
```

2023-06-29 23:55 UTC, Kou-Ro approved these changes

2023-06-30 10:23 UTC, starkoka commented
こいつに関してはマージ一番最後にやったほうが良さそうな気がする(フッター変更を確実に行うため)

2023-06-30 12:18 UTC, Kou-Ro commented
4

2023-06-30 14:06 UTC, starkoka commented
@NXVZBGBFBEN yoroshiku

2023-06-30 14:07 UTC, Kou-Ro approved these changes

2023-06-30 14:15 UTC, merged