bot-statusとメンテナンスに関するアプデ
NITKC-DEV/Kisarazu-Multi-Manager pull request #148
Opened 2023-06-29 11:38 UTC by starkoka

# 新機能及び機能の更新
 - status関数を作成(ステータスを切り替えられる関数)
 - メンテナンスモードの切り替えをmaintenance関数に移行
 - メンテナンスモード中はBOTのステータスが取り込み中になるように
 - 寮の消灯時間のときはBOTも退席中になるように
 - BOT起動時にBOTのステータスを更新するように
 - 1分毎にBOTのカスタムステータスを更新するように

# その他修正
 - 天気自動送信の時刻が間違ってた問題を修正
 - リアクションで応答するタイプのやつの確実性を高めるために0.1sの遅延を追加

2023-06-29 12:59 UTC, NXVZBGBFBEN requested changes

2023-06-29 12:59 UTC, NXVZBGBFBEN commented on botmain.js
> +const statusAndMode = require("./functions/status&mode");
拡張子ほしい

2023-06-29 12:59 UTC, NXVZBGBFBEN commented on botmain.js
> +        if(date.getHours()*100+date.getMinutes()>=204 && date.getHours()*100+date.getMinutes()<=509)status=1;
``status``は使用されてないような気がする

2023-06-29 12:59 UTC, NXVZBGBFBEN commented on botmain.js
> +        switch(time){
``default``ケースが欲しいけど好みの問題

2023-06-29 12:59 UTC, NXVZBGBFBEN commented on commands/dashboard.js
>                      let flag = -1,otherReact =[0,0];
``otherReact``は``const``にできそう

2023-06-29 12:59 UTC, NXVZBGBFBEN commented on commands/dashboard.js
> +                    sleep(100);
5行目で``require()``してる``setTimeout()``自体がPromiseを返すので以下のように記述すればいいのではないかと
```js
await setTimeout(100);
```

2023-06-29 12:59 UTC, NXVZBGBFBEN commented on commands/general.js
> +                    sleep(100);
ここも``setTimeout()``単体を使えば良さそう

2023-06-29 12:59 UTC, NXVZBGBFBEN commented on commands/general.js
>                          await interaction.editReply( `変更を取りやめました` );
句読点を統一したほうがいいかも
下の
> Permission denied : BOT開発者専用コマンドです

も含めて

2023-06-29 12:59 UTC, NXVZBGBFBEN commented on functions/status&mode.js
ファイル名に記号を使うな！！！！(発狂)

2023-06-29 12:59 UTC, NXVZBGBFBEN commented on functions/status&mode.js
> +const statusAndMode = require("./status&mode");
拡張子ほしい

2023-06-29 12:59 UTC, NXVZBGBFBEN commented on functions/status&mode.js
> +        if(date.getHours()*100+date.getMinutes()>=204 && date.getHours()*100+date.getMinutes()<=509)status=1;
パラメータ名``status``の値を上書きするのはあまりよろしくない気がしないでもない
別の変数を用意してインデックスを保持したほうがよさそう

2023-06-29 13:27 UTC, starkoka commented on functions/status&mode.js
_はどうなんですか

2023-06-29 14:03 UTC, NXVZBGBFBEN commented on functions/status&mode.js
![image](https://github.com/NITKC-DEV/Kisarazu-Multi-Manager/assets/107386214/1d8f0626-31cb-44b7-86bf-79af3f31e3b2)
発狂

2023-06-29 14:06 UTC, starkoka commented on functions/status&mode.js
草

2023-06-29 16:08 UTC, NXVZBGBFBEN submitted a review, later dismissed
``status&mode.js``は``statusAndMode.js``とかにすべきだと思うけどまあ他の人たちの意見に任せます

2023-06-30 00:22 UTC, Kou-Ro requested changes

2023-06-30 00:22 UTC, Kou-Ro commented on functions/status&mode.js
> +
定期

2023-06-30 00:22 UTC, Kou-Ro commented on functions/status&mode.js
> +const statusAndMode = require("./status&mode.js");
拡張子

2023-06-30 10:25 UTC, starkoka commented
二人の指摘事項の修正どね

2023-06-30 11:49 UTC, NXVZBGBFBEN approved these changes
```
 _______ _______ _______ _______ 
|\     /|\     /|\     /|\     /|
| +---+ | +---+ | +---+ | +---+ |
| |   | | |   | | |   | | |   | |
| |L  | | |G  | | |T  | | |M  | |
| +---+ | +---+ | +---+ | +---+ |
|/_____\|/_____\|/_____\|/_____\|
```

2023-06-30 12:18 UTC, Kou-Ro commented
1

2023-06-30 12:21 UTC, Kou-Ro approved these changes

2023-06-30 12:21 UTC, merged