nextTestの息の根を止めるプルリク
NITKC-DEV/Kisarazu-Multi-Manager pull request #152
Opened 2023-06-29 14:16 UTC by starkoka

これで1分辺り最大5回程度のDB更新とはおさらばだ

2023-06-29 14:19 UTC, starkoka commented
あ、タンマ。まだ上手く動いてないかも

2023-06-29 14:29 UTC, starkoka commented
これでヨシ

2023-06-29 16:19 UTC, NXVZBGBFBEN requested changes

2023-06-29 16:19 UTC, NXVZBGBFBEN commented on functions/dashboard.js
>                      let day = diffInMonthsAndDays(now, UNIXtest)
``day``は``const``にできそう

2023-06-30 11:47 UTC, NXVZBGBFBEN approved these changes
```
██╗      ██████╗████████╗███╗   ███╗
██║     ██╔════╝╚══██╔══╝████╗ ████║
██║     ██║  ███╗  ██║   ██╔████╔██║
██║     ██║   ██║  ██║   ██║╚██╔╝██║
███████╗╚██████╔╝  ██║   ██║ ╚═╝ ██║
╚══════╝ ╚═════╝   ╚═╝   ╚═╝     ╚═╝
```

2023-06-30 12:18 UTC, Kou-Ro commented
3

2023-06-30 14:04 UTC, Kou-Ro approved these changes

2023-06-30 14:04 UTC, merged