𝑈𝐿𝑇𝐼𝑀𝐴𝑇𝐸 𝐼𝑀𝑃𝑅𝑂𝑉𝐸𝑀𝐸𝑁𝑇 𝑇𝐼𝑀𝐸
NITKC-DEV/Kisarazu-Multi-Manager pull request #153
Opened 2023-06-29 15:43 UTC by starkoka

𝑈𝐿𝑇𝐼𝑀𝐴𝑇𝐸 𝐼𝑀𝑃𝑅𝑂𝑉𝐸𝑀𝐸𝑁𝑇 𝑇𝐼𝑀𝐸です。

# 修正点
 - 待望の #95 を実装
 - #140 を実装(checkGuild関数使用)
 - #145 を適用
 - #146 を修正
 - #150 を改善(波データ削除、概況を𝑆𝑈𝑃𝐸𝑅 𝑆𝐸𝐼𝐾𝐸𝐼 𝑇𝐼𝑀𝐸した)

2023-06-29 16:42 UTC, NXVZBGBFBEN requested changes

2023-06-29 16:42 UTC, NXVZBGBFBEN commented on commands/general.js
> +                    await interaction.reply({ content: 'このコマンドはサーバーでのみ実行できます', ephemeral: true });
283行目を含め句読点を統一したほうがよさそう

2023-06-29 16:42 UTC, NXVZBGBFBEN commented on commands/guildData.js
>                      .setFooter({ text: 'Developed by NITKC22s server Admin' });
最新じゃないかも(152行目含め)

2023-06-29 16:42 UTC, NXVZBGBFBEN commented on functions/weather.js
>          else{return String.fromCharCode(s.charCodeAt(0) - 0xFEE0);}
それぞれ``return``後は``else``必要ないかも
たぶんこれでも同じ
```js
if(s === '．')return `.`;
if(s === '　')return '';
if(s === '海')return " 海"
if(s === '後')return " 後"
return String.fromCharCode(s.charCodeAt(0) - 0xFEE0);
```

2023-06-29 16:42 UTC, NXVZBGBFBEN commented on functions/weather.js
95行目のフッタが最新じゃないかも

2023-06-29 16:43 UTC, starkoka commented on commands/guildData.js
>                      .setFooter({ text: 'Developed by NITKC22s server Admin' });
それね、このプルリクを一番最初に通すことでほかのプルリクで修正されるはず

2023-06-29 16:44 UTC, NXVZBGBFBEN commented on commands/guildData.js
>                      .setFooter({ text: 'Developed by NITKC22s server Admin' });
そういうことか～

2023-06-30 11:45 UTC, NXVZBGBFBEN approved these changes
```
  __      ______    _______   __    __   
 /\_\    /_/\___\ /\_______)\/_/\  /\_\  
( ( (    ) ) ___/ \(___  __\/) ) \/ ( (  
 \ \_\  /_/ /  ___  / / /   /_/ \  / \_\ 
 / / /__\ \ \_/\__\( ( (    \ \ \\// / / 
( (_____()_)  \/ _/ \ \ \    )_) )( (_(  
 \/_____/\_\____/   /_/_/    \_\/  \/_/  
```

2023-06-30 12:18 UTC, Kou-Ro commented
2

2023-06-30 12:40 UTC, Kou-Ro approved these changes

2023-06-30 14:03 UTC, merged