君は完璧で究極のhelp
NITKC-DEV/Kisarazu-Multi-Manager pull request #164
Opened 2023-07-02 13:41 UTC by starkoka

- admin-help実装
 - help一新(helpText.jsonにヘルプを書く形式に、StringSelectMenu化)

2023-07-02 13:42 UTC, starkoka commented
あ、ヘルプの内容は気にしないで。だから、helpText.jsonは無視していい

2023-07-02 14:02 UTC, naotiki requested changes

2023-07-02 14:02 UTC, naotiki commented on functions/help.js
> +for(let value in helpText.admin){
value使ってる？
普通の
for (let i = 0; i < helptext.admin.length; i++) {
じゃだめなの？

2023-07-02 14:02 UTC, naotiki commented on functions/help.js
> +for(let value in helpText.help){
ここも

2023-07-02 14:03 UTC, starkoka commented on functions/help.js
> +for(let value in helpText.admin){
あっ、許してください何でもしますから

2023-07-02 14:29 UTC, NXVZBGBFBEN requested changes

2023-07-02 14:29 UTC, NXVZBGBFBEN commented on functions/help.js
> +const {StringSelectMenuBuilder, StringSelectMenuOptionBuilder,EmbedBuilder, ActionRowBuilder} = require("discord.js");
コンマの後のスペースを統一したほうがよさそう

2023-07-02 14:29 UTC, NXVZBGBFBEN commented on functions/help.js
> +let adminTable = [],i=0;
``adminTable``は``const``にできそう

2023-07-02 14:29 UTC, NXVZBGBFBEN commented on functions/help.js
> +let helpTable = [];i=0;
``helpTable``は``const``にできそう

2023-07-02 14:29 UTC, NXVZBGBFBEN commented on functions/help.js
> +        .setDescription("木更津高専統合管理BOTをご利用いただきありがとうございます。\n管理者向けのヘルプでは、主に以下に記載した管理者向けのBOTの情報や機能についての説明があります。\n\n下のセレクトメニューから内容を選ぶことで、ヘルプが読めます。\n")
「ヘルプが読めます」より「ヘルプを読めます」の方が自然かな...?(個人的な感想)

2023-07-02 14:29 UTC, NXVZBGBFBEN commented on functions/help.js
> +    let newEmbed = new EmbedBuilder()
どちらも``const``にできそう

2023-07-02 14:29 UTC, NXVZBGBFBEN commented on functions/help.js
> +
定期

2023-07-02 14:29 UTC, NXVZBGBFBEN commented on functions/help.js
> +        .setDescription("木更津高専統合管理BOTをご利用いただきありがとうございます。\nヘルプでは、このBOTの機能の使い方等を確認できます。\n\n下のセレクトメニューから内容を選ぶことで、ヘルプが読めます。\n")
ヘルプを読めます

2023-07-02 14:29 UTC, NXVZBGBFBEN commented on functions/help.js
> +    let newEmbed = new EmbedBuilder()
``const``にできそう

2023-07-02 14:29 UTC, NXVZBGBFBEN commented on functions/help.js
> +
定期

2023-07-02 23:27 UTC, NXVZBGBFBEN approved these changes
```
   _       ___    _____  __  __  
  | |     / __|  |_   _||  \/  | 
  | |__  | (_ |    | |  | |\/| | 
  |____|  \___|   _|_|_ |_|__|_| 
_|"""""|_|"""""|_|"""""|_|"""""| 
"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-' 
```

2023-07-03 02:36 UTC, Kou-Ro requested changes

2023-07-03 02:36 UTC, Kou-Ro commented on functions/help.js
> +
定期

2023-07-03 02:36 UTC, Kou-Ro commented on functions/help.js
> +
定期

2023-07-03 03:48 UTC, starkoka commented
@NXVZBGBFBEN @Kou-Ro 空行削除しました

2023-07-03 04:04 UTC, Kou-Ro approved these changes

2023-07-03 05:02 UTC, naotiki approved these changes

2023-07-03 05:11 UTC, NXVZBGBFBEN approved these changes
```
      ___       ___           ___           ___     
     /\__\     /\  \         /\  \         /\__\    
    /:/  /    /::\  \        \:\  \       /::|  |   
   /:/  /    /:/\:\  \        \:\  \     /:|:|  |   
  /:/  /    /:/  \:\  \       /::\  \   /:/|:|__|__ 
 /:/__/    /:/__/_\:\__\     /:/\:\__\ /:/ |::::\__\
 \:\  \    \:\  /\ \/__/    /:/  \/__/ \/__/~~/:/  /
  \:\  \    \:\ \:\__\     /:/  /            /:/  / 
   \:\  \    \:\/:/  /     \/__/            /:/  /  
    \:\__\    \::/  /                      /:/  /   
     \/__/     \/__/                       \/__/    
```

2023-07-03 05:12 UTC, merged