スラッシュコマンド改善など
NITKC-DEV/Kisarazu-Multi-Manager pull request #176
Opened 2023-07-03 14:32 UTC by starkoka

# 修正
 - #126 を適用
 - DMで実行するとエラーでそうなコマンド&AdminコマンドをDMでブロックするように変更

# その他
- #172 を修正

2023-07-03 15:03 UTC, NXVZBGBFBEN requested changes
句読点以外は今後整形ツールでなんとでもなるはずなので最悪無視でもおｋ

2023-07-03 15:06 UTC, starkoka commented on commands/general.js
>                  await interaction.reply({ content: "DMに管理者向けメニューを送信しました。受信できていない場合、以下に該当していないかどうかご確認ください。\n・このサーバー上の他のメンバーからのDMをOFFにしている\n・フレンドからのDMのみを許可している\n・このBOTをブロックしている", ephemeral: true });
Discordのmd記法の箇条書き、バグあるから使ってない

2023-07-03 15:09 UTC, starkoka commented on commands/timeTable.js
>              const replyOptions=time=>{return{content: '削除しました。\n(このメッセージは'+time+'秒後に自動で削除されます)', ephemeral:true};};
んー、ないとすでにreplyしてるところにdeferReplyして爆発する気がする

2023-07-03 15:11 UTC, starkoka commented on commands/timeTable.js
>              const replyOptions=time=>{return{content: '削除しました。\n(このメッセージは'+time+'秒後に自動で削除されます)', ephemeral:true};};
BOT落ちはしなかったけど、普通に例外吐かれてスラッシュコマンド失敗したので(動作は一応ちゃんとしてるけど利用者側に警告が出る)、NGで

2023-07-03 15:12 UTC, starkoka commented on commands/timeTable.js
>              const replyOptions=time=>{return{content: '削除しました。\n(このメッセージは'+time+'秒後に自動で削除されます)', ephemeral:true};};
あ、replyOptionsの話?　そしたらそれはKouroからそのままもらってるから手付けたらまずそうだからそれはそれでNo

2023-07-03 15:13 UTC, NXVZBGBFBEN commented on commands/timeTable.js
>              const replyOptions=time=>{return{content: '削除しました。\n(このメッセージは'+time+'秒後に自動で削除されます)', ephemeral:true};};
あ，すまん，こういうことを意図していた
```js
const replyOptions=time=>({content: '削除しました。\n(このメッセージは'+time+'秒後に自動で削除されます)', ephemeral:true});
```

2023-07-03 15:13 UTC, NXVZBGBFBEN commented on commands/timeTable.js
>              const replyOptions=time=>{return{content: '削除しました。\n(このメッセージは'+time+'秒後に自動で削除されます)', ephemeral:true};};
これダメだっけ

2023-07-03 15:14 UTC, starkoka commented on commands/timeTable.js
>              const replyOptions=time=>{return{content: '削除しました。\n(このメッセージは'+time+'秒後に自動で削除されます)', ephemeral:true};};
わからないけど、下手に手を付けると怖いからやめておく。外部関数化したから結局今後消えるコードだし

2023-07-03 15:14 UTC, NXVZBGBFBEN commented on commands/timeTable.js
>              const replyOptions=time=>{return{content: '削除しました。\n(このメッセージは'+time+'秒後に自動で削除されます)', ephemeral:true};};
おｋ

2023-07-03 15:15 UTC, NXVZBGBFBEN submitted a review, later dismissed
あっｐろゔぇ

2023-07-03 23:24 UTC, Kou-Ro requested changes

2023-07-03 23:24 UTC, Kou-Ro commented on commands/dashboard.js
定期

2023-07-03 23:24 UTC, Kou-Ro commented on commands/general.js
句読点ありでいくの？

2023-07-04 01:52 UTC, Kou-Ro reviewed
@starkoka 
こいつら

2023-07-04 01:52 UTC, Kou-Ro commented on commands/general.js
> +                    await interaction.reply({ content: 'このコマンドはサーバーでのみ実行できます。', ephemeral: true });
ここと

2023-07-04 01:52 UTC, Kou-Ro commented on commands/general.js
> +                    await interaction.reply({ content: 'このコマンドはサーバーでのみ実行できます', ephemeral: true });
ここと

2023-07-04 01:52 UTC, Kou-Ro commented on commands/general.js
> +                    await interaction.editReply({ content: `このサーバーで誕生日を${interaction.options.getInteger('月')}月${interaction.options.getInteger('日')}日に設定しました。\n他のサーバーで通知してほしい場合は、そのサーバーでもう一度実行してください。`}
ここと

2023-07-04 01:52 UTC, Kou-Ro commented on commands/general.js
> +                    await interaction.editReply({ content: "誕生日を正しい数字で設定してください。"});
ここと

2023-07-04 01:52 UTC, Kou-Ro commented on commands/general.js
> +                    await interaction.reply({ content: 'このコマンドはサーバーでのみ実行できます。', ephemeral: true });
ここと

2023-07-04 01:52 UTC, Kou-Ro commented on commands/general.js
> +                    await interaction.editReply({ content: "このサーバーでの通知を解除しました。\n他のサーバーでも通知を止めたい場合、そのサーバーで実行してください。"});
ここと

2023-07-04 01:52 UTC, Kou-Ro commented on commands/general.js
> +                    await interaction.editReply({ content: "このサーバーではあなたの誕生日が設定されていません。\n通知を止めたいサーバーで実行してください。"});
ここと

2023-07-04 01:52 UTC, Kou-Ro commented on commands/general.js
> +                await interaction.reply({ content: "天気定期通知機能を" + interaction.options.data[0].value + "に設定しました。"});
ここ

2023-07-04 02:03 UTC, Kou-Ro commented on commands/general.js
> +                    await interaction.editReply({ content: "このサーバーでの通知を解除しました。\n他のサーバーでも通知を止めたい場合、そのサーバーで実行してください。"});
こういうのはいらなくね

2023-07-04 02:18 UTC, Kou-Ro approved these changes

2023-07-04 02:19 UTC, merged