hotfix/SecretMessage #224
NITKC-DEV/Kisarazu-Multi-Manager pull request #225
Opened 2023-07-12 04:14 UTC by Kou-Ro

### #224 everyoneメンション権限を持たないユーザーが/secretmessageでオプションに何も指定しなかったときにエラーを吐く問題を修正

2023-07-12 12:09 UTC, starkoka requested changes
- package.jsonのversionを5.0.2に
 - ttGeneration.jsの26行目、16:15ではなく16:20

2023-07-13 04:17 UTC, starkoka approved these changes
OK

2023-07-13 10:43 UTC, NXVZBGBFBEN approved these changes

2023-07-13 12:27 UTC, naotiki requested changes

2023-07-13 12:27 UTC, naotiki commented on package.json
なんで全角？

2023-07-13 12:28 UTC, Kou-Ro commented on package.json
何が？

2023-07-13 12:29 UTC, naotiki commented on package.json
> +  "version": "5.0.２",
"version": "5.0.２",
                        ^

2023-07-14 06:13 UTC, Kou-Ro commented
修正

2023-07-14 07:19 UTC, naotiki approved these changes

2023-07-14 07:28 UTC, NXVZBGBFBEN approved these changes
あっｐろゔぇ

2023-07-14 10:59 UTC, starkoka approved these changes
LGTM

2023-07-14 10:59 UTC, merged