Prettier導入
NITKC-DEV/Kisarazu-Multi-Manager pull request #238
Opened 2023-12-03 15:00 UTC by NXVZBGBFBEN

## 変更内容
+ Prettier追加
+ Husky&Lint-stagedによるコミット前自動整形

---
Closes #137

2023-12-03 15:30 UTC, Kou-Ro reviewed
```js
if (
```
(スペース)はキモくね

2023-12-03 15:33 UTC, Kou-Ro reviewed
オブジェクト型
```js
const hoge =  { hoge };
```
の波括弧のスペースもなー
(要審議)

2023-12-03 15:35 UTC, Kou-Ro reviewed
ラムダ式の引数にカッコつけるのは少々厳しすぎやしませんかね、、、

2023-12-03 15:36 UTC, Kou-Ro commented
> オブジェクト型
> 
> ```js
> const hoge =  { hoge };
> ```
> 
> の波括弧のスペースもなー (要審議)

せめて配列の[hoge]と統一してほしい

2023-12-03 15:37 UTC, Kou-Ro commented on deploy-commands.js
> +    //ファイルの数だけ
これはちょっと謎い
これが良しとされているのか？？？

2023-12-03 15:38 UTC, Kou-Ro commented on deploy-commands.js
> +    if (mode == "キャンセル") {
多分 @NXVZBGBFBEN 関係ないんだけど
===じゃないとまずくね

2023-12-03 15:40 UTC, NXVZBGBFBEN commented on deploy-commands.js
> +    if (mode == "キャンセル") {
こいつぁESLint導入の段階で修正になるかと

2023-12-03 15:42 UTC, Kou-Ro commented on functions/birthday.js
> +            } catch {}
```js
if () {
}
else{
}
```
なのに
```js
try {
} catch {}

2023-12-03 15:44 UTC, Kou-Ro commented on functions/dashboard.js
> +    let months = 0,
変数宣言は一行のほうが普通じゃないか？

2023-12-03 15:46 UTC, Kou-Ro commented on functions/dashboard.js
> +    } else {
```js
if(){
}
else if() {
} else{
}
```
になってるきがする

2023-12-03 15:48 UTC, NXVZBGBFBEN commented on deploy-commands.js
> +    //ファイルの数だけ
これは本来``for``の上に書かれているべきじゃねえかな(手動修正しときます)
開き波括弧の右側には何も書かないのがPrettier流らしい

2023-12-03 15:50 UTC, Kou-Ro commented on functions/guildDataSet.js
> + weatherChannel:
これはテンプレだからインデント崩されると困る

2023-12-03 15:52 UTC, Kou-Ro commented on functions/guildDataSet.js
> +                $set: {
いやまあそうなんだけど分かりづらくね

2023-12-03 15:54 UTC, Kou-Ro commented on functions/help.js
> +        .setColor(0x00a0ea)
16進は大文字統一のほうがいいのでは

2023-12-03 15:54 UTC, NXVZBGBFBEN commented on functions/guildDataSet.js
> + weatherChannel:
範囲ignoreしときます

2023-12-03 15:54 UTC, NXVZBGBFBEN commented on functions/help.js
> +        .setColor(0x00a0ea)
~~Prettierの開発者に言ってくれ~~

2023-12-03 15:55 UTC, Kou-Ro commented on functions/help.js
> +        .setColor(0x00a0ea)
できないの？

2023-12-03 15:55 UTC, NXVZBGBFBEN commented on functions/dashboard.js
> +    let months = 0,
そもそも1つの``let``句に対して1つの変数が宣言されるべき
手動修正します

2023-12-03 15:55 UTC, Kou-Ro commented on functions/dashboard.js
> +    let months = 0,
えぇ、、

2023-12-03 15:57 UTC, NXVZBGBFBEN commented on functions/birthday.js
> +            } catch {}
``if-else``も``try-catch``と同じじゃない？ (l.14以降参照)

2023-12-03 15:58 UTC, Kou-Ro commented on functions/birthday.js
> +            } catch {}
https://github.com/NITKC-DEV/Kisarazu-Multi-Manager/pull/238#discussion_r1413139790
参照

2023-12-03 16:01 UTC, NXVZBGBFBEN commented on functions/dashboard.js
> +    } else {
``else if``なくね？
![image](https://github.com/NITKC-DEV/Kisarazu-Multi-Manager/assets/107386214/0c82ae76-6e90-467f-b195-1e5e3e5cbbcd)

2023-12-03 16:03 UTC, NXVZBGBFBEN commented on functions/help.js
> +        .setColor(0x00a0ea)
できない

2023-12-03 16:04 UTC, NXVZBGBFBEN commented on functions/help.js
> +        .setColor(0x00a0ea)
そもそもPrettierが「俺がルールだ！」的なフォーマッタなので...

2023-12-03 16:09 UTC, NXVZBGBFBEN commented on functions/guildDataSet.js
> +                $set: {
これは多分どうしようもないと思われ

2023-12-03 16:10 UTC, NXVZBGBFBEN commented
> オブジェクト型
> 
> ```js
> const hoge =  { hoge };
> ```
> 
> の波括弧のスペースもなー (要審議)

これは設定で変更できる

2023-12-03 16:11 UTC, NXVZBGBFBEN commented
> ラムダ式の引数にカッコつけるのは少々厳しすぎやしませんかね、、、

これも無効にできる ~~(俺は括弧つける派だけど)~~

2023-12-03 16:12 UTC, NXVZBGBFBEN commented
> ```js
> if (
> ```
> 
> (スペース)はキモくね

``if``と条件式の隙間？
これのことなら変更不可，そもそも制御構文なのでスペースあった方が良い気がするが

2023-12-03 16:22 UTC, Kou-Ro commented on functions/weather.js
> +        color = "FAA401";
おっと、今度は急に16進大文字になったぞ

2023-12-03 16:22 UTC, Kou-Ro commented on functions/dashboard.js
> +    } else {
ああー
見間違いだわ

2023-12-03 16:22 UTC, Kou-Ro commented on functions/dashboard.js
> +    } else {
問題点を修正
```js
if () {
}
else if () {
}
else {
}
```
のほうが良くね

2023-12-03 16:22 UTC, Kou-Ro commented on botmain.js
> +                        ).send({ embeds: [embed[4]] });
元のほうがいいと思うけどなー
まあしょうがないか

2023-12-03 16:30 UTC, Kou-Ro commented on functions/weather.js
> +        if (s === "．") return `.`;
@starkoka 
なんでここバッククォートなん？？？

2023-12-03 16:35 UTC, NXVZBGBFBEN commented on functions/weather.js
> +        color = "FAA401";
文字列だからだね

2023-12-03 16:46 UTC, NXVZBGBFBEN commented on functions/dashboard.js
> +    } else {
これはどうしようもない

2023-12-03 16:48 UTC, Kou-Ro requested changes
とりまRequest

2023-12-03 16:52 UTC, Kou-Ro commented
多分
let hoge, fugo;
結構ある

2023-12-03 16:53 UTC, NXVZBGBFBEN commented
> 多分 let hoge, fugo; 結構ある

たぶんESLintで一網打尽にされる

2023-12-07 13:41 UTC, NXVZBGBFBEN commented
@Kou-Ro 再レビューお願いします
Prettierの仕様で変更不可なところは全部そのまま

2023-12-07 14:22 UTC, Kou-Ro approved these changes
あんましっかり見てないけどまたなんか問題があったら都度お願いするわ

2023-12-10 23:33 UTC, NXVZBGBFBEN commented
@starkoka @naotiki 

時間ある時に確認お願いします...!
この次はESLintを導入予定

2023-12-11 01:46 UTC, naotiki approved these changes

2023-12-11 02:40 UTC, Kou-Ro commented
変更行数が多く、複数コミットあるのでSquashにします

2023-12-11 02:41 UTC, merged