Feature/#138 eslint
NITKC-DEV/Kisarazu-Multi-Manager pull request #240
Opened 2024-02-21 10:44 UTC by NXVZBGBFBEN

# #138 ESLint導入
- ESLintを導入しました．エラー解消のため一部設計変更を行ないました．
- ディレクトリ構造を変更しました．``env``ディレクトリ内は``templates``ディレクトリを除き全てignore対象です．
- npmのスクリプトを刷新しました．Intellijの実行構成にも反映済みです．

Closes #138

2024-02-28 08:32 UTC, starkoka commented
やります

2024-02-28 13:00 UTC, starkoka requested changes
とりあえず1点だけ
・Intellijの実行構成で、重複起動を許可しないように変更したほうがいいかも

2024-02-28 13:04 UTC, naotiki commented on src/commands/timeTable.js
> +            if (Number.isNaN(grade)) {
[要検証] 
常にgradeには文字列しか入らないため常にfalseを返す可能性
https://zenn.dev/nekoya/articles/67e03a84633591

2024-02-28 13:13 UTC, naotiki commented on src/commands/timeTable.js
> +            if (Number.isNaN(grade)) {
```suggestion
            if (Number.isNaN(parseInt(grade)) {
```

2024-02-28 14:29 UTC, NXVZBGBFBEN commented
> とりあえず1点だけ ・Intellijの実行構成で、重複起動を許可しないように変更したほうがいいかも

これ，対策済みのつもり
Nodeじゃなくてnpmの実行構成に切り替えたんだけど，もしかしたらmainブランチから移動したりするとNodeの構成が残ったままになるかも

2024-04-04 13:33 UTC, Kou-Ro commented on package.json
> +    "@types/node": "^20.10.4",
コレ必要？

2024-04-04 14:30 UTC, Kou-Ro commented on src/commands/general.js
> +            // const reply = await interaction.deferReply();
コメントアウトされたまま放置されている

2024-04-04 19:30 UTC, NXVZBGBFBEN commented on package.json
> +    "@types/node": "^20.10.4",
IntellijのNode支援機能有効化したら自動追加されたような記憶がある

2024-04-04 19:44 UTC, NXVZBGBFBEN commented on src/commands/general.js
> +            // const reply = await interaction.deferReply();
未使用だったのでコメントアウトしたんだな
結局どうすればいいんだこれ

2024-04-05 12:08 UTC, Kou-Ro commented on src/commands/general.js
> +            // const reply = await interaction.deferReply();
動くなら消していいんじゃね

2024-04-05 12:09 UTC, Kou-Ro commented on package.json
> +    "@types/node": "^20.10.4",
なるほどね

2024-04-05 12:15 UTC, NXVZBGBFBEN commented on src/commands/general.js
> +            // const reply = await interaction.deferReply();
``interaction.deferReply()``に副作用があるから消すとマズいかも
返り値使わないなら修正するけど，いかが？(修正して``await interaction.deferReply()``)だけにする

2024-07-11 06:31 UTC, naotiki approved these changes
Looks Good For ME

2024-07-14 13:23 UTC, starkoka approved these changes
確認済みなのにLGTMするの忘れてたとか言えない

2024-07-14 16:08 UTC, merged